# Generated by Django 4.2.4 on 2023-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Employee_name", models.CharField(max_length=100)),
                ("Employee_address", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Start_Date", models.DateTimeField()),
                ("End_Date", models.DateTimeField()),
                ("Salary", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Login_time", models.TimeField()),
            ],
        ),
    ]
